import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { servisSupabase, yoneticiDogrula } from "@/lib/supabase/admin";
import { editorTurkusuKaydet, katkiDurumuGuncelle, kulturIcerigiKaydet, kullaniciRoluGuncelle } from "./actions";

export const metadata: Metadata = { title:"Editör Masası", robots:{index:false,follow:false} };
export const dynamic = "force-dynamic";

export default async function AdminSayfasi() {
  const yetki = await yoneticiDogrula(); if (!yetki) redirect("/giris?next=/admin");
  const db = servisSupabase();
  const [{data:katkilar},{data:profiller},{data:turkuler},{data:icerikler}, authUsers] = await Promise.all([
    db.from("hafiza_katkilari").select("*").order("olusturulma",{ascending:false}).limit(80),
    db.from("profiller").select("id,kullanici_adi,gorunen_ad,rol,olusturulma").order("olusturulma",{ascending:false}).limit(100),
    db.from("editor_turkuler").select("slug,baslik,yore,durum,guncellenme").order("guncellenme",{ascending:false}).limit(100),
    db.from("kultur_icerikleri").select("id,tur,slug,baslik,il,durum,guncellenme").order("guncellenme",{ascending:false}).limit(100),
    yetki.profil.rol === "admin" ? db.auth.admin.listUsers({page:1,perPage:100}) : Promise.resolve({data:{users:[]},error:null}),
  ]);
  const email = new Map((authUsers.data?.users ?? []).map(u=>[u.id,u.email]));
  const bekleyen = (katkilar??[]).filter(x=>x.durum==="bekliyor").length;
  return <main className="mx-auto max-w-7xl px-4 py-10">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-kilim">Güvenli yönetim alanı</p><h1 className="mt-2 font-serif text-4xl font-semibold text-ceviz">Editör Masası</h1><p className="mt-2 text-ceviz-light">Katkıları doğrulayın, kullanıcı rollerini ve yeni içerikleri yönetin.</p></div><span className="rounded-full bg-ceviz px-4 py-2 text-sm font-semibold text-parsomen">{yetki.profil.rol}</span></header>
    <section className="mt-7 grid gap-3 sm:grid-cols-4">{[["Bekleyen katkı",bekleyen],["Kullanıcı",profiller?.length??0],["Editör türküsü",turkuler?.length??0],["Kültür içeriği",icerikler?.length??0]].map(([a,s])=><div key={a} className="rounded-2xl border border-toprak/20 bg-white/50 p-4"><strong className="block font-serif text-3xl text-ceviz">{s}</strong><span className="text-sm text-ceviz-light">{a}</span></div>)}</section>
    <AdminBaslik id="katkilar" baslik="Katkı kuyruğu" aciklama="Kaynağı, yayın iznini ve ekli materyali kontrol etmeden onaylamayın." />
    <div className="space-y-3">{(katkilar??[]).map(k=><article key={k.id} className="rounded-2xl border border-toprak/25 bg-white/55 p-4"><div className="flex flex-wrap justify-between gap-2"><div><strong className="text-ceviz">{k.katki_turu} · {k.il}</strong><p className="text-xs text-ceviz-light">{k.turku_slug||"Genel arşiv"} · {new Date(k.olusturulma).toLocaleDateString("tr-TR")}</p></div><span className="rounded-full bg-toprak/10 px-3 py-1 text-xs">{k.durum}</span></div><p className="mt-3 max-w-4xl whitespace-pre-wrap text-sm leading-6 text-ceviz-light">{k.aciklama}</p><p className="mt-2 text-xs">Yayın izni: <b>{k.yayin_izni?"Var":"Yok"}</b> · Kaynak onayı: <b>{k.kaynak_onayi?"Var":"Yok"}</b>{k.kaynak_kisi?` · Kaynak: ${k.kaynak_kisi}`:""}</p><form action={katkiDurumuGuncelle} className="mt-3 grid gap-2 sm:grid-cols-[180px_1fr_auto]"><input type="hidden" name="id" value={k.id}/><select name="durum" defaultValue={k.durum} className="admin-input"><option>bekliyor</option><option>inceleniyor</option><option>onaylandi</option><option>reddedildi</option></select><input name="editor_notu" defaultValue={k.editor_notu??""} placeholder="Editör notu veya gerekçe" className="admin-input"/><button className="admin-button">Kaydet</button></form></article>)}</div>
    <AdminBaslik id="turkuler" baslik="Türkü ekle veya güncelle" aciklama="Kaynaklı editör kayıtları sürümlü olarak Supabase’te tutulur."/><form action={editorTurkusuKaydet} className="admin-form"><input name="baslik" required placeholder="Türkü başlığı" className="admin-input"/><input name="yore" required placeholder="Yöre" className="admin-input"/><input name="slug" placeholder="Slug (boşsa otomatik)" className="admin-input"/><select name="durum" className="admin-input"><option>taslak</option><option>incelemede</option><option>yayinda</option><option>arsivlendi</option></select><input name="ozan" placeholder="Ozan" className="admin-input"/><input name="soz_yazari" placeholder="Söz yazarı" className="admin-input"/><input name="derleyen" placeholder="Derleyen" className="admin-input"/><input name="kaynak_kisi" placeholder="Kaynak kişi" className="admin-input"/><input name="etiketler" placeholder="Etiketler, virgülle" className="admin-input sm:col-span-2"/><textarea name="ozet" required minLength={30} placeholder="Özet (en az 30 karakter)" className="admin-input sm:col-span-2" rows={3}/><textarea name="hikaye" required minLength={80} placeholder="Kaynaklı hikâye (en az 80 karakter)" className="admin-input sm:col-span-2" rows={6}/><input name="kaynak_baslik" placeholder="Kaynak başlığı" className="admin-input"/><input name="kaynak_url" type="url" placeholder="https:// kaynak" className="admin-input"/><button className="admin-button sm:col-span-2">Türküyü kaydet</button></form>
    <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{(turkuler??[]).map(t=><div key={t.slug} className="rounded-xl border border-toprak/20 p-3 text-sm"><b>{t.baslik}</b><span className="block text-xs text-ceviz-light">{t.yore} · {t.durum}</span></div>)}</div>
    <AdminBaslik id="kultur" baslik="Kültür, kurs ve gelir içerikleri" aciklama="Rota, şehir tarihi, kurs, etkinlik ve açıkça etiketlenmiş sponsor içeriklerini yönetin."/><form action={kulturIcerigiKaydet} className="admin-form"><select name="tur" className="admin-input"><option value="kultur-rotasi">Kültür rotası</option><option value="sehir-tarihi">Şehir tarihi</option><option value="kurs">Kurs</option><option value="etkinlik">Etkinlik</option><option value="sponsor">Sponsor</option></select><input name="baslik" required placeholder="Başlık" className="admin-input"/><input name="il" placeholder="İl" className="admin-input"/><input name="slug" placeholder="Slug" className="admin-input"/><select name="durum" className="admin-input"><option>taslak</option><option>incelemede</option><option>yayinda</option><option>arsivlendi</option></select><input name="dis_url" type="url" placeholder="Kurs/bilet/kurum bağlantısı" className="admin-input"/><input name="gorsel_url" type="url" placeholder="Lisanslı görsel URL" className="admin-input sm:col-span-2"/><textarea name="ozet" required minLength={20} placeholder="Kısa özet" className="admin-input sm:col-span-2" rows={2}/><textarea name="icerik" required minLength={40} placeholder="Doğal, kaynaklı ve profesyonel içerik" className="admin-input sm:col-span-2" rows={6}/><button className="admin-button sm:col-span-2">İçeriği kaydet</button></form>
    <AdminBaslik id="kullanicilar" baslik="Kullanıcılar" aciklama="E-posta yalnızca admin rolünde ve sunucu tarafında görüntülenir."/><div className="overflow-x-auto rounded-2xl border border-toprak/25"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-ceviz text-parsomen"><tr><th className="p-3">Kullanıcı</th><th>E-posta</th><th>Kayıt</th><th>Rol</th></tr></thead><tbody>{(profiller??[]).map(p=><tr key={p.id} className="border-t border-toprak/15"><td className="p-3 font-semibold">@{p.kullanici_adi}</td><td>{email.get(p.id)??"Yalnızca admin görebilir"}</td><td>{new Date(p.olusturulma).toLocaleDateString("tr-TR")}</td><td>{yetki.profil.rol==="admin"?<form action={kullaniciRoluGuncelle} className="flex gap-2"><input type="hidden" name="id" value={p.id}/><select name="rol" defaultValue={p.rol} className="rounded-lg border px-2 py-1"><option>uye</option><option>editor</option><option>admin</option></select><button className="text-kilim underline">Uygula</button></form>:p.rol}</td></tr>)}</tbody></table></div>
    <p className="mt-8 text-xs text-ceviz-light">Spotify içeriği, kullanıcı e-postaları ve özel katkı dosyaları gelir/sponsor hedeflemesinde kullanılmaz. <Link href="/gizlilik" className="underline">Gizlilik ilkeleri</Link></p>
  </main>;
}

function AdminBaslik({id,baslik,aciklama}:{id:string;baslik:string;aciklama:string}) { return <header id={id} className="mb-4 mt-12 border-b border-toprak/20 pb-3"><h2 className="font-serif text-2xl font-semibold text-ceviz">{baslik}</h2><p className="mt-1 text-sm text-ceviz-light">{aciklama}</p></header> }
